# Generated by Django 5.1.6 on 2025-02-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.FloatField()),
                ('total_vulnerabilities', models.IntegerField()),
                ('report_path', models.CharField(max_length=255)),
            ],
        ),
    ]
