import { createContext, useContext, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const UI_TRANSLATIONS = {
  en: {
    reports: "Reports",
    runAnalysis: "Run Analysis",
    running: "Running...",
    noReportYet: "No report available yet. Run an analysis from Settings or start one here.",
    findingsWorkspace: "Vulnerability Findings Workspace",
    inspectFindings: "Inspect severity, categories, crash metadata, and analytics from completed runs.",
    vulnerabilities: "Vulnerabilities",
    searchVulnerabilities: "Search vulnerabilities...",
    details: "Details",
    previous: "Previous",
    next: "Next",
    settingsTitle: "Account, Security, And Runtime Settings",
    settingsSubtitle: "Manage profile details, preferences, corpus uploads, seed selection, and execution limits.",
    commandCenter: "Command Center",
    targetIntake: "Target Intake",
    settings: "Settings",
    secureWorkspace: "Secure analysis workspace",
    logout: "Logout",
    findingsSnapshot: "Findings Snapshot",
    runNewAnalysis: "Run New Analysis",
    runningAnalysis: "Running Analysis...",
    lastGenerated: "Last Generated",
    riskScore: "Risk Score",
    totalFindings: "Total Findings",
    categoryBreakdown: "Category Breakdown",
    noCategoryData: "No category data available.",
    analysisContext: "Analysis Context",
    targetPlatform: "Target Platform",
    version: "Version",
    processor: "Processor",
    architecture: "Architecture",
    overallRiskScore: "Overall Risk Score",
    risk: "Risk",
    noVulnerabilities: "No vulnerabilities found.",
    page: "Page",
    of: "of",
    severeCritical: "Critical",
    severeHigh: "High",
    severeMedium: "Medium",
    severeLow: "Low",
    severeAll: "All",
    crashInspectionMetadata: "Crash Inspection Metadata",
    severity: "Severity",
    type: "Type",
    timestamp: "Timestamp",
    component: "Component",
    cveId: "CVE ID",
    affectedService: "Affected Service",
    recommendation: "Recommendation",
    mark: "Mark",
    saveSettings: "Save Settings",
  },
  es: {
    reports: "Informes",
    runAnalysis: "Ejecutar analisis",
    running: "Ejecutando...",
    noReportYet: "Todavia no hay informe. Ejecuta un analisis desde Configuracion o inicia uno aqui.",
    findingsWorkspace: "Espacio de Hallazgos de Vulnerabilidades",
    inspectFindings: "Inspecciona severidad, categorias, metadatos de fallos y analitica de ejecuciones completadas.",
    vulnerabilities: "Vulnerabilidades",
    searchVulnerabilities: "Buscar vulnerabilidades...",
    details: "Detalles",
    previous: "Anterior",
    next: "Siguiente",
    settingsTitle: "Configuracion de Cuenta, Seguridad y Ejecucion",
    settingsSubtitle: "Administra perfil, preferencias, corpus, semilla y limites de ejecucion.",
    commandCenter: "Centro de Comando",
    targetIntake: "Ingreso de Objetivo",
    settings: "Configuracion",
    secureWorkspace: "Espacio de analisis seguro",
    logout: "Cerrar sesion",
    findingsSnapshot: "Resumen de Hallazgos",
    runNewAnalysis: "Ejecutar Nuevo Analisis",
    runningAnalysis: "Ejecutando analisis...",
    lastGenerated: "Ultima Generacion",
    riskScore: "Puntaje de Riesgo",
    totalFindings: "Hallazgos Totales",
    categoryBreakdown: "Desglose por Categoria",
    noCategoryData: "No hay datos de categoria.",
    analysisContext: "Contexto del Analisis",
    targetPlatform: "Plataforma Objetivo",
    version: "Version",
    processor: "Procesador",
    architecture: "Arquitectura",
    overallRiskScore: "Puntaje Global de Riesgo",
    risk: "Riesgo",
    noVulnerabilities: "No se encontraron vulnerabilidades.",
    page: "Pagina",
    of: "de",
    severeCritical: "Critica",
    severeHigh: "Alta",
    severeMedium: "Media",
    severeLow: "Baja",
    severeAll: "Todas",
    crashInspectionMetadata: "Metadatos de Inspeccion de Fallo",
    severity: "Severidad",
    type: "Tipo",
    timestamp: "Marca de tiempo",
    component: "Componente",
    cveId: "ID CVE",
    affectedService: "Servicio Afectado",
    recommendation: "Recomendacion",
    mark: "Marcar",
    saveSettings: "Guardar Configuracion",
  },
  fr: {
    reports: "Rapports",
    runAnalysis: "Lancer l'analyse",
    running: "Execution...",
    noReportYet: "Aucun rapport disponible. Lancez une analyse depuis Parametres ou ici.",
    findingsWorkspace: "Espace des Resultats de Vulnerabilites",
    inspectFindings: "Consultez severite, categories, metadonnees de crash et analyses.",
    vulnerabilities: "Vulnerabilites",
    searchVulnerabilities: "Rechercher des vulnerabilites...",
    details: "Details",
    previous: "Precedent",
    next: "Suivant",
    settingsTitle: "Parametres Compte, Securite et Execution",
    settingsSubtitle: "Gerez profil, preferences, corpus, semence et limites d'execution.",
    commandCenter: "Centre de Commande",
    targetIntake: "Reception de Cible",
    settings: "Parametres",
    secureWorkspace: "Espace d'analyse securise",
    logout: "Se deconnecter",
    findingsSnapshot: "Apercu des Resultats",
    runNewAnalysis: "Lancer une Nouvelle Analyse",
    runningAnalysis: "Analyse en cours...",
    lastGenerated: "Derniere Generation",
    riskScore: "Score de Risque",
    totalFindings: "Total des Resultats",
    categoryBreakdown: "Repartition par Categorie",
    noCategoryData: "Aucune donnee de categorie.",
    analysisContext: "Contexte d'Analyse",
    targetPlatform: "Plateforme Cible",
    version: "Version",
    processor: "Processeur",
    architecture: "Architecture",
    overallRiskScore: "Score Global de Risque",
    risk: "Risque",
    noVulnerabilities: "Aucune vulnerabilite trouvee.",
    page: "Page",
    of: "sur",
    severeCritical: "Critique",
    severeHigh: "Elevee",
    severeMedium: "Moyenne",
    severeLow: "Faible",
    severeAll: "Toutes",
    crashInspectionMetadata: "Metadonnees d'Inspection du Crash",
    severity: "Severite",
    type: "Type",
    timestamp: "Horodatage",
    component: "Composant",
    cveId: "ID CVE",
    affectedService: "Service Affecte",
    recommendation: "Recommandation",
    mark: "Marquer",
    saveSettings: "Enregistrer les Parametres",
  },
  de: {
    reports: "Berichte",
    runAnalysis: "Analyse starten",
    running: "Laeuft...",
    noReportYet: "Noch kein Bericht verfuegbar. Starten Sie eine Analyse in Einstellungen oder hier.",
    findingsWorkspace: "Arbeitsbereich fuer Schwachstellenbefunde",
    inspectFindings: "Pruefen Sie Schweregrad, Kategorien, Crash-Metadaten und Analysen.",
    vulnerabilities: "Schwachstellen",
    searchVulnerabilities: "Schwachstellen suchen...",
    details: "Details",
    previous: "Zurueck",
    next: "Weiter",
    settingsTitle: "Konto-, Sicherheits- und Laufzeit-Einstellungen",
    settingsSubtitle: "Verwalten Sie Profil, Praeferenzen, Corpus, Seed und Laufzeitgrenzen.",
    commandCenter: "Steuerzentrale",
    targetIntake: "Zielaufnahme",
    settings: "Einstellungen",
    secureWorkspace: "Sicherer Analysebereich",
    logout: "Abmelden",
    findingsSnapshot: "Befunduebersicht",
    runNewAnalysis: "Neue Analyse starten",
    runningAnalysis: "Analyse laeuft...",
    lastGenerated: "Zuletzt erzeugt",
    riskScore: "Risiko-Score",
    totalFindings: "Gesamtbefunde",
    categoryBreakdown: "Kategorieaufteilung",
    noCategoryData: "Keine Kategoriedaten verfuegbar.",
    analysisContext: "Analysekontext",
    targetPlatform: "Zielplattform",
    version: "Version",
    processor: "Prozessor",
    architecture: "Architektur",
    overallRiskScore: "Gesamtrisiko-Score",
    risk: "Risiko",
    noVulnerabilities: "Keine Schwachstellen gefunden.",
    page: "Seite",
    of: "von",
    severeCritical: "Kritisch",
    severeHigh: "Hoch",
    severeMedium: "Mittel",
    severeLow: "Niedrig",
    severeAll: "Alle",
    crashInspectionMetadata: "Crash-Inspektionsmetadaten",
    severity: "Schweregrad",
    type: "Typ",
    timestamp: "Zeitstempel",
    component: "Komponente",
    cveId: "CVE-ID",
    affectedService: "Betroffener Dienst",
    recommendation: "Empfehlung",
    mark: "Markieren",
    saveSettings: "Einstellungen Speichern",
  },
  hi: {
    reports: "Reports",
    runAnalysis: "Analysis chalayein",
    running: "Chal raha hai...",
    noReportYet: "Abhi report uplabdh nahi hai. Settings se analysis chalayein ya yahin se start karein.",
    findingsWorkspace: "Vulnerability Findings Workspace",
    inspectFindings: "Severity, category, crash metadata aur analytics dekhein.",
    vulnerabilities: "Vulnerabilities",
    searchVulnerabilities: "Vulnerabilities search karein...",
    details: "Details",
    previous: "Pichla",
    next: "Agla",
    settingsTitle: "Account, Security aur Runtime Settings",
    settingsSubtitle: "Profile, preferences, corpus, seed aur execution limits manage karein.",
    commandCenter: "Command Center",
    targetIntake: "Target Intake",
    settings: "Settings",
    secureWorkspace: "Secure analysis workspace",
    logout: "Logout",
    findingsSnapshot: "Findings Snapshot",
    runNewAnalysis: "Naya Analysis Chalayein",
    runningAnalysis: "Analysis chal raha hai...",
    lastGenerated: "Last Generated",
    riskScore: "Risk Score",
    totalFindings: "Total Findings",
    categoryBreakdown: "Category Breakdown",
    noCategoryData: "Category data uplabdh nahi hai.",
    analysisContext: "Analysis Context",
    targetPlatform: "Target Platform",
    version: "Version",
    processor: "Processor",
    architecture: "Architecture",
    overallRiskScore: "Overall Risk Score",
    risk: "Risk",
    noVulnerabilities: "Koi vulnerability nahi mili.",
    page: "Page",
    of: "of",
    severeCritical: "Critical",
    severeHigh: "High",
    severeMedium: "Medium",
    severeLow: "Low",
    severeAll: "All",
    crashInspectionMetadata: "Crash Inspection Metadata",
    severity: "Severity",
    type: "Type",
    timestamp: "Timestamp",
    component: "Component",
    cveId: "CVE ID",
    affectedService: "Affected Service",
    recommendation: "Recommendation",
    mark: "Mark",
    saveSettings: "Settings Save Karein",
  },
};

const REPORT_VALUE_MAP = {
  es: {
    CRITICAL: "Critica",
    HIGH: "Alta",
    MEDIUM: "Media",
    LOW: "Baja",
    Buffer: "Buffer",
    Overflow: "Desbordamiento",
    Recommendation: "Recomendacion",
    component: "componente",
  },
  fr: {
    CRITICAL: "Critique",
    HIGH: "Elevee",
    MEDIUM: "Moyenne",
    LOW: "Faible",
    Buffer: "Tampon",
    Overflow: "Depassement",
    Recommendation: "Recommandation",
    component: "composant",
  },
  de: {
    CRITICAL: "Kritisch",
    HIGH: "Hoch",
    MEDIUM: "Mittel",
    LOW: "Niedrig",
    Buffer: "Puffer",
    Overflow: "Ueberlauf",
    Recommendation: "Empfehlung",
    component: "Komponente",
  },
  hi: {
    CRITICAL: "Critical",
    HIGH: "High",
    MEDIUM: "Medium",
    LOW: "Low",
    Buffer: "Buffer",
    Overflow: "Overflow",
    Recommendation: "Sujhav",
    component: "component",
  },
};

const translateText = (text, lang) => {
  if (!text || lang === "en") return text;
  const map = REPORT_VALUE_MAP[lang] || {};
  let translated = String(text);
  Object.entries(map).forEach(([from, to]) => {
    translated = translated.split(from).join(to);
  });
  return translated;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem("aigesxLanguage") || "en");

  const setPreferredLanguage = (lang) => {
    setLanguage(lang || "en");
    localStorage.setItem("aigesxLanguage", lang || "en");
  };

  const t = (key) => {
    const selected = UI_TRANSLATIONS[language] || UI_TRANSLATIONS.en;
    return selected[key] || UI_TRANSLATIONS.en[key] || key;
  };

  const translateReportData = (report) => {
    if (!report || language === "en") return report;
    const cloned = structuredClone(report);
    const vulnerabilities = cloned?.detailed_findings?.vulnerabilities;
    if (Array.isArray(vulnerabilities)) {
      cloned.detailed_findings.vulnerabilities = vulnerabilities.map((item) => ({
        ...item,
        severity: translateText(item.severity, language),
        type: translateText(item.type, language),
        description: translateText(item.description, language),
        recommendation: translateText(item.recommendation, language),
        component: translateText(item.component, language),
        affected_service: translateText(item.affected_service, language),
      }));
    }
    return cloned;
  };

  const value = useMemo(
    () => ({
      language,
      setPreferredLanguage,
      t,
      translateReportData,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
