# Generated by Django 5.1.6 on 2025-02-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanreport',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='scanreport',
            name='total_vulnerabilities',
        ),
    ]
